@URL_ROOT=http://localhost:8080
@URL_BASE={{URL_ROOT}}/v2


####
# @name index
GET {{URL_BASE}}
Accept: application/json

###
# @name addUserFail
POST {{URL_BASE}}/user
Accept: application/json
Content-Type: application/json

###
# @name addUser
POST {{URL_BASE}}/user
Accept: application/json
Content-Type: application/json

{
  "username": "username1",
  "firstName": "user2",
  "lastName": "name3"
}

###
@user_name={{addUser.response.body.$.username}}

# @name getUserByName
GET {{URL_BASE}}/user/{{user_name}}
Accept: application/json
Content-Type: application/json
