@URL_ROOT=http://localhost:8080
@URL_BASE={{URL_ROOT}}/v2


####
# @name index
GET {{URL_BASE}}
Accept: application/json


###
# @name addUser
POST {{URL_BASE}}/user
Accept: application/json
Content-type: application/json

{
  "username": "user1 name2",
  "firstName": "user1",
  "lastName": "name2",
  "email": "mailaddress3",
  "password": "password1234",
  "phone": "0123456789",
  "userStatus": 0
}